### ISSUE TITLE
The overall HTML page and the basic <form> with submit button

### ISSUE THREAD

**Issue by ameliaburger** [cpolyukh/coordination#3]

**Comment by cpolyukh** [comment]
Created the basic form structure with a reset and submit button. Added necessary AngularJS to the HTML to fields that are required for validation (did not add any other methods for validation besides checking for required fields). Also added a .gitignore file.

**Comment by ameliaburger** [comment]
it looks like the .idea folder is still in the repo even though it's in the .gitignore file

**Comment by cpolyukh** [comment]
Yeah I committed this before noticing it was an issue. I'll get rid of it in the next commit

**Comment by ameliaburger** [comment]
beautiful. I'll close this then :+1:

**Comment by cpolyukh** [comment]
Okay phew I think the .idea folder is gone for good now :100:
